### ISSUE TITLE
Unable to resolve symbol

### ISSUE THREAD

**Issue by matthiasn** [aiba/lein-count#1]
Hi Aaron,

This plugin sound like it would be useful at times. I tried using it, however, and ran into this:

`clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: second' in this context, compiling:(aiba/lein_count/constant_wrapping_reader.clj:772:19)`

Same error in different projects when running `lein count`. Maybe you can have a look what could be the issue.

Cheers,
Matthias

**Comment by bensu** [comment]
This is might be from having the wrong `tools.reader` version on the classpath. `second'` from `clojure/tools/reader/impl/utils.clj` was not there in earlier versions of `tools.reader`. 

Try `lein deps :tree > deps.txt` and then search for `tools.reader`. Do you have any old versions there?

@aiba do you specially import `org.clojure/tools.reader` in the project you are using `lein-count` from?

**Comment by matthiasn** [comment]
Thanks, I checked that but no old versions in there.

**Comment by aiba** [comment]
Sounds like a tools.reader version issue.  `lein-count` depends on `[org.clojure/tools.reader "1.0.0-beta4"]`.  `constant_wrapping_reader.clj` requires `[clojure.tools.reader.impl.utils :refer :all]`, which should contain `second'`.

I don't specially import tools.reader when I run `lein count`.

@matthiasn if you try adding `[lein-count "1.0.2"]` to `~/.lein/profiles.clj`, then are you able to run it outside of a project?  For example:

```
$ cd /tmp/
$ lein count :artifact ring/ring-core 1.6.0
```

**Comment by matthiasn** [comment]
Yes that works, I added it to `~/.lein/profiles.clj` anyway. But inside a few projects, it does not. Not sure if it's a good idea to rely on some internals of the reader lib here, especially something added more recently. Even the latest and greatest ClojureScript as of today still pulls in `"1.0.0-beta3"`.

**Comment by aiba** [comment]
> Not sure if it's a good idea to rely on some internals of the reader lib here

`lein-count` explicitly depends on version `"1.0.0-beta4"` of tools.reader.

I would think that if you use a plugin that depends on `some-library` version 2, and your regular project dependencies depend on the same `some-library` version 1, then lein would just put version 2 in the classpath.  Maybe that's a bad assumption.  I'll have to research how lein resolves plugin dependencies and get back to you on this.

Thanks for reporting this issue!

**Comment by jeaye** [comment]
I just got this as well.

```bash
$ lein count
Retrieving lein-count/lein-count/1.0.2/lein-count-1.0.2.pom from clojars
Retrieving doric/doric/0.9.0/doric-0.9.0.pom from clojars
Retrieving lein-count/lein-count/1.0.2/lein-count-1.0.2.jar from clojars
Retrieving doric/doric/0.9.0/doric-0.9.0.jar from clojars
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: second' in this context, compiling:(aiba/lein_count/constant_wrapping_reader.clj:772:19)
 at clojure.lang.Compiler.analyze (Compiler.java:6688)
    clojure.lang.Compiler.analyze (Compiler.java:6625)
    clojure.lang.Compiler$InvokeExpr.parse (Compiler.java:3766)
    ...
Caused by: java.lang.RuntimeException: Unable to resolve symbol: second' in this context
 at clojure.lang.Util.runtimeException (Util.java:221)
    clojure.lang.Compiler.resolveIn (Compiler.java:7164)
    clojure.lang.Compiler.resolve (Compiler.java:7108)
    ...
```

**Comment by aiba** [comment]
@matthiasn @jeaye mind running `lein version` and paste the output so we can see what version of lein you're using?  I'm having trouble reproducing this.

**Comment by jeaye** [comment]
On Tue, May 30, 2017 at 01:09:01PM -0700, Aaron Iba wrote:
> @matthiasn @jeaye mind running `lein version` and paste the output so we can see what version of lein you're using?  I'm having trouble reproducing this.

Leiningen 2.7.1 on Java 1.8.0_121 OpenJDK 64-Bit Server VM

I'm on Arch Linux.

**Comment by aiba** [comment]
I suspect something in `project.clj` is disturbing the plugin dependencies and preventing `lein-count` from getting the correct version of `tools.reader`.  Can someone who is experiencing this problem paste their `project.clj` so I can try to reproduce this?

**Comment by matthiasn** [comment]
This one for example doesn't work: <https://github.com/matthiasn/BirdWatch/blob/master/Clojure-Websockets/MainApp/project.clj>. 

Using `Leiningen 2.7.1 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM`.

**Comment by aiba** [comment]
For BirdWatch, it's got to be some kind of plugin dependency conflict.  If you comment out `[codox "0.10.3"]` from `project.clj`, then it works fine.

This would make sense because `codox` depends on `clojurescript` which depends on `tools.reader "1.0.0-beta3"`.

What baffles me is that `lein deps :plugin-tree` shows that it's using `tools.reader "1.0.0-beta4"`.  Let's keep this ticket open and investigate more later.  For now, you can comment out codox and it should work.

Thanks for the help tracking this down.

**Comment by briantrice** [comment]
Is this function the one in question? https://github.com/clojure/tools.reader/blob/3a0aaafbfdbc69b010e447a38e5ed628e0019068/src/main/cljs/cljs/tools/reader/impl/utils.cljs#L96

Because that's such a tiny utility that you could do without it until such time as the version of reader you want is more widely adopted. As it is, I can't get past this without cleaning my project every time I want to run count.

**Comment by aiba** [comment]
We could copy that 1-liner function `second'`, but I'm not optimistic that would solve this.  If you look at [all the tools.reader changes from 0.10.0-alpha3 to 1.0.0-beta3](https://github.com/clojure/tools.reader/compare/tools.reader-0.10.0-alpha3...tools.reader-1.0.0-beta4), you'll see a lot of stuff changed.

What I'd really like to figure out is why lein doesn't link up the version of tools.reader that is explicitly depended on by lein-count.
