### ISSUE TITLE
Duplicate source files

### ISSUE THREAD

**Issue by polymeris** [aiba/lein-count#2]
I tried lein-count with [this project](https://github.com/polymeris/re-frame-realword-example-app) and was surprised at the 4k line count!

Turns out most files where counted 4 times for some reason.

**Comment by aiba** [comment]
This is indeed a bug.  Working on a fix.

**Comment by aiba** [comment]
Fixed by bba7ff360c059305cc2c4da2f0b45fe89cfc8fac

Thank you for reporting this!
