### ISSUE TITLE
:artifact should work without version 

### ISSUE THREAD

**Issue by ikitommi** [aiba/lein-count#3]
... and find the latest version avaible, just like [lein-ancient](https://github.com/xsc/lein-ancient).

```clj
;; explicit version
lein count :artifact metosin/spec-tools 0.2.0

;; without version finds the latest version (0.2.0)
lein count :artifact metosin/spec-tools 
```

nice lib!

**Comment by aiba** [comment]
I agree that would be nice, but it appears nontrivial to figure out the latest version of an artifact.  We'd either have to depend on lein-ancient or duplicate [its logic for finding the latest version](https://github.com/xsc/lein-ancient/blob/master/ancient-clj/src/ancient_clj/core.clj).

I'm going to close as wontfix for now, unless someone can think of a better way.
