### ISSUE TITLE
Doesn't work when there is no test directory

### ISSUE THREAD

**Issue by matthiasn** [aiba/lein-count#7]
Just tried in different projects I have cloned locally and stumbled a problem when checking my local copy of the [sente](https://github.com/ptaoussanis/sente) library:

```
$ lein count
File or directory not found: test
```
Pretty sure this is not intended.

**Comment by aiba** [comment]
This was the original intention, but I agree with you it would be better to not fail when a directory is missing so I changed it to a nonfatal warning.

Thanks for reporting!

Fixed by Fixed by 7dfd787eb2fe09a678ebedaf250bf2ab1e64009c
