### ISSUE TITLE
pre vs post macro expansion counting

### ISSUE THREAD

**Issue by fhur** [aiba/lein-count#8]
I have the following file:

```clojurescript
(ns foo.bar
  (:require [cljs.spec :as s]))
```

When running `lein count :by-file some-folder/`

I get the following output (only showing the relevant line):
```
| cljs | src/foo/bar.cljs                          |             2 |    45 |
```

The line count is correct, but the node count is way to high. I guess this is true after macro expansion, but shouldn't the node count be pre-expansion?

**Comment by aiba** [comment]
Thanks for reporting.  This is actually a bug related to how the reader handles constant metadata, not related to macro expansion.
